server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowCredentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
      routes:
        - id: content-command
          uri: lb://CONTENT-COMMAND
          predicates:
            - Path=/content-command/**
            - Method=POST,PATCH,DELETE,OPTIONS
          filters:
            - RewritePath=/content-command/(?<segment>.*), /$\{segment}

        - id: content-query
          uri: lb://CONTENT-QUERY
          predicates:
            - Path=/content-query/**
            - Method=GET,OPTIONS
          filters:
            - RewritePath=/content-query/(?<segment>.*), /$\{segment}

        - id: search-service
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/search-service/**
            - Method=GET,OPTIONS
          filters:
            - RewritePath=/search-service/(?<segment>.*), /$\{segment}

        - id: media-server
          uri: lb://MEDIA-SERVER
          predicates:
            - Path=/media-server/**
            - Method=POST,OPTIONS
          filters:
            - RewritePath=/media-server/(?<segment>.*), /$\{segment}

        - id: follow-service
          uri: http://localhost:8070
          predicates:
            - Path=/follow-service/**
            - Method=GET, POST, PUT, OPTIONS
          filters:
            - RewritePath=/follow-service/(?<segment>.*), /$\{segment}

        - id: notification-server
          uri: http://localhost:8071
          predicates:
            - Path=/notification-server/**
            - Method=GET, POST, OPTIONS
          filters:
            - RewritePath=/notification-server/(?<segment>.*), /$\{segment}