spring:
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: jikji
    consumer:
      enable-auto-commit: true
      auto-offset-reset: earliest
  datasource:
    url: jdbc:mysql://localhost:3306/insta_clone_auth_db
    username: root
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: auth-service

jwtSecretKey: sgdevcampinstacloneprojectauthserver

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
server:
  port: 8081
